config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :topics, only: [:index, :show] do
      resources :conversations, only: [:index, :show]
    end
    resources :messages, only: [:create]
    resource :sessions, only: [:create]
    get 'conversations' => 'conversations#recent'
  end

  resource :sessions, only: [:create]
  resources :users, only: [:create, :show]
  resources :topics, only: [:index, :show] do
    resources :conversations, only: [:index, :show, :new, :create]
  end
  resources :messages, only: [:create]

  get 'conversations' => 'conversations#recent'
  root 'topics#index'
  get 'register' => 'users#new'
  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :topic, touch: true
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :messages, -> {order(created_at: :desc)}
  validates :name, presence: true
  validates :author, presence: true
  validates :topic, presence: true
  validates_associated :messages

  delegate :name, to: :topic, prefix: true, allow_nil: true
  delegate :id, to: :topic, prefix: true, allow_nil: true

  def latest_message
    messages.order(id: :desc).first
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.by_recency
    order(updated_at: :desc)
  end

  def self.get_recently_active_convos
    by_recency.limit(10)
  end

  def self.with_no_messages
    includes(:messages).where(messages: {id:nil})
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :message
  validates_uniqueness_of :message, scope: :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation, touch: true
  belongs_to :user

  validates :content, presence: true

  delegate :username, to: :user, prefix: false, allow_nil: true

  def in_caps
    content.upcase if content
  end

  def self.my_recent(user)
    where(user_id: user.id).order(updated_at: :desc).limit(5)
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  has_many :conversations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :messages
  has_many :conversations
  validates :email, presence: true

  def get_recent_messages
    self.messages.order(created_at: :desc).limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @topic = Topic.find(params[:topic_id])
    @conversations = @topic.conversations.order(updated_at: :desc)
  end

  def show
    @conversation = Conversation.find(params[:id])
  end

  def recent
    @conversations = Conversation.by_recency
  end

  def new
    topic_id = params[:topic_id][0]
    @topic = Topic.find(topic_id)
    p @topic
    @conversation = Conversation.new

    if request.xhr?
      render partial: "form", locals: {topic: @topic, conversation: @conversation}
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @conversation = @topic.conversations.new(name: params[:conversation][:name])
    @conversation.user_id = current_user.id

    if @conversation.save
      if request.xhr?
        render partial: 'conversation', locals: {conversation: @conversation}
      else
        redirect_to topic_conversations_path(@topic)
      end
    else
      render :'conversations/new'
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    msg = Message.new(message_params)
    if msg.save
      if request.xhr?
        render partial: "message", locals: {message: msg}
      else
        redirect_to topic_conversation_path(msg.conversation.topic, msg.conversation)
      end
    else
      @conversation = Conversation.find(params[:message][:conversation_id])
      flash.now.alert = msg.errors.full_messages.join(', ')
      render 'conversations/show'
    end
  end

  private
  def message_params
    params.require(:message).permit(:conversation_id, :content).merge(user: current_user)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    u = User.find_by(username: params[:username])
    if u && u.authenticate(params[:password])
      session[:user_id] = u.id
      redirect_to root_path
    else
      render '/session/new'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @categories = Category.includes(:topics).order(:display_order)
    @recent_conversations = Conversation.get_recently_active_convos
  end

  def show
    redirect_to topic_conversations_path(Topic.find(params[:id]))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if (@user.save)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_crumbs.html.erb
<div id="breadcrumbs">
<%= link_to 'All topics', topics_path %>
<% if @conversation && @conversation.id %>
   | <%= link_to @conversation.topic_name, topic_path(@conversation.topic) %>
<% end %>
</div>

app/views/conversations/_conversation.html.erb
<li>
  <%= link_to conversation.name, topic_conversation_path(conversation.topic, conversation) %> <% if conversation.latest_message %> Latest from <%= conversation.latest_message.username %> at <%= conversation.latest_message.created_at.to_formatted_s(:forum) %> <% end %>
</li>

app/views/conversations/_form.html.erb
<%= form_for [@topic, @conversation] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/_new.html.erb
<div id="new-conversation-form">
  <%= form_for @conversation do |f|%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :topic_id, value: @topic.id %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name%>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/conversations/_new_conversation_entry.html.erb
<li><%= link_to @conversation.name, conversation_path(@conversation) %></li>

app/views/conversations/index.html.erb
<h1>Conversations in <%= @topic.name %> </h1>

<% if current_user %>
  <div id="convo-form-div">
    <p><%= link_to "Start a Conversation", new_topic_conversation_path, id: "start-convo-link"%></p>
  </div>
<% end %>

<ul id='conversation-list'>
  <%= render @conversations %>
</ul>

app/views/conversations/new.html.erb
<%= render 'form' %>

app/views/conversations/recent.html.erb
<h1>Recent Conversations</h1>
  <ul>
    <%= render @conversations %>
  </ul>

app/views/conversations/show.html.erb
<h1 class="conversation"><%= @conversation.name %></h1>
<div id="conversation" >
  <div id="lede">Started by <%= @conversation.author.username %>  at <%= @conversation.created_at.to_formatted_s(:forum) %></div>
  <div id="all-messages">
    <%= render @conversation.messages %>
  </div>
</div>

<% if current_user %>
<div class="form">
<h2>Add your message</h2>
  <%= form_for Message.new do |f| %>
    <%= f.hidden_field :conversation_id, value: @conversation.id %>
    <div>
      <%= f.label :author %>
      <%= text_field_tag :throwaway, current_user.username, disabled: true %>
    </div>
    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
    <div>
      <%= f.submit  %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBulletin</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <% if flash.any?  %>
      <div id="flash">
        <% flash.each do |type, message| %>
          <div class="<%= type %> ">
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if current_user %>
      Hello <%= link_to current_user.username, user_path(current_user) %>
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Login', login_path %>
      <%= link_to 'Register', register_path %>
    <% end %>
      <%= render partial:'crumbs' %>
      <%= yield %>
  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message" data-id="m<%= message.id %>">
  <div class="header">From
    <span class="author"><%= message.username %></span>
  at
    <span class="timestamp"><%= message.created_at.to_formatted_s(:forum) %></span>
    <span class="score"><%= message.score %></span>
    <% if current_user && !message.liked_by_user?(current_user)%>
    <span class="like-button"><a href="/messages/<%= message.id %>/like">Like</a></span>
    <% end %>
  </div>

  <div class="body"><%= message.content %> </div>
</div>

app/views/messages/_new.html.erb
  <%= form_for @message do |f| %>
  <%= f.hidden_field :conversation_id, value: @conversation.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
      <div><%= f.label :content, "New Message" %></div>
      <div><%= f.text_area :content, :cols => "200", :rows => "20" %></div>
    </div>
    <%= f.submit %>
  <% end %>

app/views/messages/_new_message.html.erb
<li><%=@message.content%></li>

app/views/messages/index.html.erb
<h1><%= @conversation.name %></h1>

<% @conversation.messages.each do |message| %>
  <p><%= link_to message.get_message_intro, conversation_message_path(@conversation, message) %></p>
<% end %>


<% if logged_in? %>
  <%= link_to "Add message", new_conversation_message_path(@conversation)  %>
<% end %>

app/views/messages/new.html.erb
<%= form_for [@conversation, @message] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit "Create message" %>
<% end %>

app/views/messages/recent.html.erb
<h1>My Recent Messages</h1>
  <ul>
    <%= render @messages %>
  </ul>

app/views/messages/show.html.erb
<h1><%= @message.get_message_intro %></h1>

<h3><%= @message.content  %></h3>

app/views/session/new.html.erb
<h2>Log in, baby!</h2>

<%= form_tag session_index_path do %>
<div>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
</div>
<div>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
</div>
<%= submit_tag 'Log in!' %>
<% end %>

app/views/topics/_topic.html.erb
<div>
  <%= link_to topic.name, topic_path(topic) %>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>
<% @categories.each do |cat| %>
  <h2><%= cat.name %></h2>
  <table class="topic_list">
    <tr>
      <th class="topic_name">Topic Name</th>
      <th class="topic_post">Last post</th>
    </tr>
    <%= render cat.topics %>
  </table>

<% end %>

<h1>Recently Active Conversations</h1>
<table class="convo_list">

    <tr>
      <th class="topic_name">Conversation Name</th>
      <th class="topic_post">Updated At</th>
    </tr>
    <% @recent_conversations.each do |convo| %>
      <tr>
        <td class="name"><%= link_to convo.name, topic_conversation_path(convo.topic, convo) %></td>
        <td class="post"><%= convo.updated_at.to_formatted_s(:forum) %></td>
      </tr>
    <% end %>
 </table>

app/views/topics/show.html.erb
<h2><%= @topic.name %></h2>

<%= form_tag conversation_create_path do %>
<input type="hidden" name="topic_id" value="<%= @topic.id %>"/>
<%= label_tag 'Start a new conversation'%>
<%= text_field_tag :name %>
<%= submit_tag 'Get it started!' %>
<% end %>


<div>
  <h3>Recently Updated</h3>
  <%= render @recent_convos %>
</div>

<div>
  <h3>Archived Conversations</h3>
  <%= render @old_convos %>
</div>

app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for @user do |f| %>
   <fieldset>
   <div>
     <%= f.label :username %>
     <%= f.text_field :username %>
   </div>
   <div>
     <%= f.label :email %>
     <%= f.text_field :email %>
   </div>
   <div>
     <%= f.label :password %>
     <%= f.password_field :password %>
   </div>
   <div>
     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation %>
   </div>
   <div>
     <%= f.submit %>
   </div>
   </fieldset>
<% end %>
<% if @user.errors.any?  %>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<h3>Conversations you started:</h3>
<% @user.conversations.each do |convo| %>
  <h4><%= link_to convo.name, topic_conversation_path(convo.topic, convo) %></h4>
<% end %>

<h3>Your Most Recent Messages:</h3>
<% if @user.messages.count > 0 %>
  <% @user.get_recent_messages.each do |msg| %>
    <h4><%= msg.content %></h4>
  <% end %>
<% else %>
  <h4>You have no recent messages.</h4>
<% end %>

app/views/welcome/index.html.erb
<h1><%= link_to "Welcome to the Bulletin!", topics_path %></h1>